### ISSUE TITLE
将您重定向的次数过多 nginx

### ISSUE THREAD

**Issue by sunnoy** [kjukjuatnk/ss-panel-v3-mod#514]
跟新了最近更新后，打开出现网页出现   将您重定向的次数过多

**Comment by glzjin** [comment]
@sunnoy 开 debug

**Comment by sunnoy** [comment]
$newResponse = $response->withStatus(405);
		$newResponse->getBody()->write($this->view()->assign("pic","/theme/".(Auth::getUser()->isLogin==false?Config::get("theme"):Auth::getUser()->theme)."/images/error/405/".$pic)->display('405.tpl'));
        return $newResponse;
    }
	
	public function page500($request, $response, $args)
    {
        $pics=scandir(BASE_PATH."/public/theme/".(Auth::getUser()->isLogin==false?Config::get("theme"):Auth::getUser()->theme)."/images/error/500/");
		if(count($pics)>2)
		{
			$pic=$pics[rand(2,count($pics)-1)];
		}
		else
		{
			$pic="5001.png";
		}
		
		$newResponse = $response->withStatus(500);



不知道是不是 这个  

想看其他东西 请移步网址 www.lovexdd.ml  此时已开启debug  
![qq 20161227093437](https://cloud.githubusercontent.com/assets/19342276/21488208/ba3760fa-cc17-11e6-9036-5ca760e814b5.png)

**Comment by glzjin** [comment]
@sunnoy php.ini disable_function 把 scandir 函数去掉

**Comment by sunnoy** [comment]
去掉也不行，正好借此机会更换了网站vps，vir那个便宜货老关我机器。谢谢查看^_^
