### ISSUE TITLE
赵老师，麻烦看下后端连接数据库的问题吧 = =

### ISSUE THREAD

**Issue by halo1094** [kjukjuatnk/ss-panel-v3-mod#517]
![s5w 6xni1 pu5bqdf sid](https://cloud.githubusercontent.com/assets/20459519/21500762/231acaa2-cc7d-11e6-9deb-36114b1f6956.png)
翻过之前的issue了 = =没找到 赵老师帮忙看下吧 谢谢了

**Comment by HanC890** [comment]
看更新日志,12月16日的到后面的步骤都来一遍
[更新日志](https://github.com/glzjin/ss-panel-v3-mod/issues/72)

**Comment by leosejin** [comment]
前面issue有答案。
