### ISSUE TITLE
资料编辑当中的两步验证二维码有问题

### ISSUE THREAD

**Issue by WayChan** [kjukjuatnk/ss-panel-v3-mod#519]
赵大侠，由于两步验证生成的url里面包含中文字符串，会导致生成的二维码无法被Google Authenticator识别，
getUrl()函数应该将$urlencoded = 'otpauth://totp/'.$name.'?secret='.$secret.'';改为
$urlencoded = 'otpauth://totp/'.urlencode($name).'?secret='.$secret.'';

对包含中文字段的变量做urlencode编码即可被软件正常识别。

**Comment by glzjin** [comment]
@WayChan 谢谢，下一个版本修复，

**Comment by WayChan** [comment]
@glzjin 看了一下您最新的版本，貌似您是添加到Models/User.php里面，我个人是更改到Utils/GA.php。因为您在Utils/GA.php 的 getQRCodeGoogleUrl( )函数段有代码$urlencoded = urlencode('otpauth://totp/'.$name.'?secret='.$secret.'');
如果在Models/User.php 的getGAurl( )函数段 做urlEncode编码的话，会导致getQRCodeGoogleUrl( )对$name字段做二次编码。

**Comment by glzjin** [comment]
@WayChan 试试就知道了=、=

**Comment by WayChan** [comment]
@glzjin  仔细瞧了一下，getQRCodeGoogleUrl( );该段函数貌似并未对其有所使用。虽然是调取api生成QRCode。最终只调用了getUrl( )结合js脚本来生成页面的QRCode。 此issue可以关闭了。谢谢回答。
