### ISSUE TITLE
登录后台管理，显示500，怎么办？还有有一次倒是搭好了，节点老是失败

### ISSUE THREAD

**Issue by CxiaoyuN** [kjukjuatnk/ss-panel-v3-mod#520]
呜呜呜

**Comment by number018** [comment]
兄弟，和你一样，搭建好几次进后台都是500错误

**Comment by HanC890** [comment]
是不是config开了redis但是服务器没装?
你把redis换成cookie看看

**Comment by number018** [comment]
我再搭建一次，是哪里的config?该修改哪里呢？

**Comment by HanC890** [comment]
> 12.然后让我们回到 ss-panel 的配置上来，
cd /home/wwwroot/ss.panel

cp config/.config.php.example config/.config.php

nano config/.config.php

这里的config,里面有中文标注,有一行是让你开redis或者cookie,标注推荐的是redis
但是如果服务器没安装的话
网站就会500
所以你干脆选cookie算了

**Comment by number018** [comment]
好的，我试试，谢谢啦~

**Comment by number018** [comment]
是cookie的，进用户中心500，后台里中专也是500  其他没问题

**Comment by Alicesonw** [comment]
刚刚更新一下就出现了，尴尬

**Comment by Ehco1996** [comment]
我也是，今天刚更新 就出现了这样的问题，谁能来解答一下？

**Comment by Alicesonw** [comment]
弱弱问下怎么git老版本

**Comment by Alicesonw** [comment]
现在这个少了个好多东西？？少了这么多文件

**Comment by Ehco1996** [comment]
好像是route.php 的原因

**Comment by Alicesonw** [comment]
我退了回去16号版本 可用 我去对对源码……还有我创建不来节点……

**Comment by Ehco1996** [comment]
问一下16号的版本在哪里可以找到？

**Comment by Alicesonw** [comment]
https://github.com/glzjin/ss-panel-v3-mod/tree/f535a558f7d901cc41421362f1e0e5d0f91cb39e

**Comment by glzjin** [comment]
@Ehco1996 每日 tips 第四期：

如何正确地排查与反馈问题。

注意，此处的问题指的是功能上，技术上的问题，你运营上的问题别来找我(不过其实就算是符合条件的问题我都不一定有时间回答)。

所以，接下来讲一下如何正确地排查和提出问题。

关于排查问题：

当你遇到一个问题时，请首先确认你的操作是否正确符合界面上的提示，以及是否正确参照说明来进行搭建，升级等操作。如果没有，请你自己仔细检查哪一步有问题。

当你确认完自己的操作无误之后，接下来就该抓取错误信息了。后端的错误信息好说，就是终端输出的日志信息，如果你是 按照安装说明里的 supervisord 设置而后运行的，那么日志就在 /var/log/mu.log (/var/log 下没有就到 /tmp 下看看，有 mu 打头的 log 文件没)里，看这个文件，不要觉得自己看不懂，里面的英文都很基础的，看完你就会发现哪里出毛病了。如果你看完确定自己解决不了，那么就发个 issue 到后端那个项目上，详细描述现象，并附上日志，会有人来看看的。

而对于前端抓取错误信息，你要做的就是首先将 debug 开关打开，这个开关在 config/.config.php 就是你安装时候编辑的那个设置文件里，看到

$System_Config['debug'] = 'false'; 

将其改为

$System_Config['debug'] = 'true';

就打开了 debug 开关了。

再回到你失败的操作上，例如你打开某个页面报 500，那么就重新打开那个页面，你就会发现它并没有跳转到 500 默认页了，会出现详细的错误信息。仔细看，你会发现很多东西的。甚至于你看完就知道哪里错了。当然，如果你实在不明白，就发个 issue 到前端那，附上详细的现象描述和 debug 界面输出的错误信息，有人会去看的。

又比如那你遇到的是执行某个请求时无返回(就一个白框弹出来之类的)，这时请保持 debug 开关打开，用浏览器抓这个请求的返回信息。具体抓取步骤请看下面的链接(Firefox 的，Chrome 的话自己上网搜)。

https://developer.mozilla.org/zh-CN/docs/Tools/Network_Monitor

然后看返回信息，一般你也能知道你怎么错了，会写出来的。如果还是不明白，就发 issue 吧，附上详细的现象描述和这个返回信息。



特别是发 issue 时，不要就丟个“xxx不行，求解”之类的话，你这样根本解决不了问题。你调试和打字嫌累，别人回答你更加嫌累呢。说话就说详细，这样才有助于解决问题。

特别是别说自己是小白，即便你真的是小白。你弱，你并没有理。

就这样，晚安。

**Comment by Alicesonw** [comment]
多谢教导，这错误太多了我放不上来……

**Comment by Ehco1996** [comment]
@glzjin 
谢谢指导，可是我打开debug之后，首页就会报错，一共22个报错 
第一个是config.php 里的地11行
retutn $System_config[key]；报错，
具体我没有学过php 只会一点简单的Python 看不懂源码
希望指教一下！

**Comment by glzjin** [comment]
@Ehco1996 发截图

**Comment by Alicesonw** [comment]
![m d nee2f94qfk4fh w b v](https://cloud.githubusercontent.com/assets/8704178/21577445/9890af02-cf95-11e6-8812-1a42f38e87af.png)

**Comment by glzjin** [comment]
@Alicesonw 为什么你升级的时候就不愿意看看更新日志呢？

**Comment by Alicesonw** [comment]
我数据库好像回档了……

**Comment by Ehco1996** [comment]
@glzjin 
![2016-12-31 7 46 58](https://cloud.githubusercontent.com/assets/24697284/21577460/2d9415ee-cf96-11e6-8a9c-275de72edf1e.png)

**Comment by glzjin** [comment]
@Ehco1996 别删配置项

**Comment by Ehco1996** [comment]
@glzjin  谢谢，我把配置项补齐了。之后也出现了 @Alicesonw 一样的问题，我第一次用github 不知道怎么看日志 我去找找找，谢谢你了
@Alicesonw 请问你解决了吗？

**Comment by Alicesonw** [comment]
我数据库缺了relay这表导致的

**Comment by Ehco1996** [comment]
@Alicesonw 
谢谢，你就用户中心会报错么？我把relay表补进去之后，用户中心可以了，可是在线ip进去还是报错，
我又尝试了一下其他的界面 也有的会报错，是不是需要把all.sql再导入一次？可是那样的话数据库里原本的数据怎么办，
![2016-12-31 8 46 56](https://cloud.githubusercontent.com/assets/24697284/21577579/17fc323e-cf9b-11e6-8515-10c6d64af37c.png)
谢谢！

**Comment by Alicesonw** [comment]
@Ehco1996 那几十个sql不是摆设……

**Comment by Ehco1996** [comment]
@Alicesonw  就是我要把所有的sql都导入进去么？
可是我看安装教程里只要导入最新的all.sql导入就ok了呀
谢谢！

**Comment by Alicesonw** [comment]
@Ehco1996 现在的话导入28 跟29就行了，这应该是更新数据库用的，还有QQwry.dat不见了……

**Comment by Ehco1996** [comment]
@Alicesonw 是的，我也导入了28 29之后看上去没问题了，但是在线ip的时候也是qqwry不见了，
还有我 php xcat 的时候 会这样
![2016-12-31 9 03 05](https://cloud.githubusercontent.com/assets/24697284/21577619/97e37574-cf9c-11e6-8815-6e3d504b312b.png)

**Comment by Ehco1996** [comment]
@Alicesonw 解决了，重新生成一个管理员账户，就会自动生产qqwry.dat了。
目前一切正常

总结一下 ：1、config配置项不要增改 2、升级时候记得看日志，3、 增加新的数据库，4、同步用户需要新的管理员。

@glzjin  谢谢大大
