### ISSUE TITLE
魔改的浏览器兼容性太欠缺了

### ISSUE THREAD

**Issue by alstarking** [kjukjuatnk/ss-panel-v3-mod#521]
测试好几天，来回换了N个浏览器，有时候就登陆不上去。点登陆没反应，比如登陆的时候， 输入邮箱的时候“邮箱”2个字跟输入的邮箱重叠，"邮箱"2个字不上跳。。有时候就好使，手机用UC浏览器登陆进去后点左上角点 ≡  调不出管理面板，有的页面就能调出。哎

**Comment by glzjin** [comment]
@alstarking 你网络太差 资源没加载全

**Comment by alstarking** [comment]
我的网络100M的，很正常，如果安装原版的重来没出过这样的问题。。能不能是我VPS的网络太差导致的？？

**Comment by glzjin** [comment]
@alstarking 是噢 反正是资源没加载全

**Comment by alstarking** [comment]
哎，总打不开，我以为是我系统的问题。重做了系统还是这样，我上别人用模板的网站，依然如此。。哎

**Comment by glzjin** [comment]
@alstarking 把你站点发出来？

**Comment by alstarking** [comment]
。。。。现在正常。。突然就好了，我来回刷新无数回，清除cookie无数回，我用了 2345加速浏览器，猎豹浏览器、IE 11.0、360极速浏览器、谷歌浏览器。。老大，这是不是为了美观、华丽，加入了某些代码特效之类的，才造成的我所说的这个兼容性的问题？

**Comment by glzjin** [comment]
@alstarking 没有 别人都没问题

**Comment by alstarking** [comment]
好吧。。目前正常了。再研究研究，老大的回复速度真快。。我以为我留言后，明天才能得到回复呢，没想到真速度。。跟在线聊天似的。QAQ2333333

**Comment by imoldchen** [comment]
我发现兼容最好的居然是微软的 EDGE
