### ISSUE TITLE
流量统计和smtp一直不生效 到底为啥呢

### ISSUE THREAD

**Issue by ymg5206** [kjukjuatnk/ss-panel-v3-mod#527]
节点列表里的节点状态不能正常显示，看不到 在线人数 服务器状态等等

smtp设置后怎么都用不了 用的是腾讯企业邮
# smtp
$System_Config['smtp_host'] = 'smtp.exmail.qq.com';
$System_Config['smtp_username'] = 'admin';
$System_Config['smtp_port'] = '465';
$System_Config['smtp_name'] = 'admin';
$System_Config['smtp_sender'] = 'admin@vpn.me';
$System_Config['smtp_passsword'] = '邮箱密码';
$System_Config['smtp_ssl'] = 'true';
这是我的设置  邮箱方式已改为smtp

请问这2个问题一般是什么原因啊 ，找了很多资料 都没解决 求助啊！！！作者大大 
http://

**Comment by glzjin** [comment]
@ymg5206 请具体描述 还有你用的什么后端？这个邮箱用不了就换个后端

**Comment by ymg5206** [comment]
后端用的就是你提供的这个

>`https://github.com/glzjin/shadowsocks/wiki/%E8%AF%B4%E6%98%8E%E4%BB%A5%E5%8F%8A%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95
`
这是ssr配置文件 http://1.2016.ml/ssr.txt
这是panel配置文件http://1.2016.ml/config.txt

第一个问题是panel里面 服务器状态不显示 http://1.2016.ml/1.png

第二个问题就是邮箱收不到邮件 smtp怎么都不行
试了mailgun也收不到
是我设置的格式问题嘛
还是设置完需要重启 这是mailgun的
# mailgun
$System_Config['mailgun_key'] = 'key-0e5d3ca69b0596eee91c61746789b712';
$System_Config['mailgun_domain'] = 'https://api.mailgun.net/v3/vpn.me/messages';
$System_Config['mailgun_sender'] = 'admin@vpn.me';

**Comment by glzjin** [comment]
@ymg5206 你节点id错了

**Comment by ymg5206** [comment]
。。。我的天。。这个真没注意。。。以为都放在一组里

**Comment by ymg5206** [comment]
邮箱用企业邮箱不行嘛

**Comment by glzjin** [comment]
@ymg5206 我哪知道

**Comment by ymg5206** [comment]
这可是你的作品啊啊啊啊啊啊。。。 mailgun的那几个格式呢。。
是不是这个config改了以后需要重启postfix啊

**Comment by glzjin** [comment]
@ymg5206 我保证不了也没义务保证每个邮箱的smtp都能用，所以这个自己解决吧。

**Comment by ymg5206** [comment]
我就是想问下这几个对后缀有要求嘛。username name sender

**Comment by ymg5206** [comment]
我再试试别的邮箱吧，感谢作者 真心感谢，功能真的太好用了，还这么耐心的解答。
再次感谢！！！学习学习！！

**Comment by lithromantic** [comment]
你的smtp 配置错了 username为邮箱帐号
