### ISSUE TITLE
麻烦作者了

### ISSUE THREAD

**Issue by helaobibi** [kjukjuatnk/ss-panel-v3-mod#529]
你好，本人新手，首先感谢作者做出一个很好的sspanel
今天想试着研究下，搭建完前台，运行最后2步的时候报错
运行php -n xcat createAdmin
downloading....
Warning: gzuncompress(): data error in /data/wwwroot/ss.luacn.net/app/Command/XCat.php on line 195
finish....Initialized empty Git repository in /data/wwwroot/ss.luacn.net/public/ssr-download/.git/
感觉第一个报错好像不影响，添加了管理员账号一切正常
第二个报错运行php xcat syncusers
Send sync mail to user: 1PHP Warning:  stream_socket_enable_crypto(): SSL: Connection reset by peer in /data/wwwroot/ss.luacn.net/vendor/phpmailer/phpmailer/class.smtp.php on line 355
PHP Notice:  fwrite(): send of 6 bytes failed with errno=32 Broken pipe in /data/wwwroot/ss.luacn.net/vendor/phpmailer/phpmailer/class.smtp.php on line 978
感觉是smtp发邮件地方有问题，是不是要改什么php.ini参数，google了一圈没找到解答，麻烦作者看下，谢谢了

**Comment by glzjin** [comment]
@helaobibi 添加第二个或更多管理员直接注册一个普通用户然后设置为管理员

**Comment by helaobibi** [comment]
管理员账号都没什么问题，现在好像发邮件好像缺少一个php的拓展。。。
