### ISSUE TITLE
赵老师，求帮忙看看国内中转报错

### ISSUE THREAD

**Issue by masonyeung** [kjukjuatnk/ss-panel-v3-mod#533]
今天刚升级完面板和后端，按照说明一步步走的，后端一切没问题。
但国内中转安装完后报错如下
![image](https://cloud.githubusercontent.com/assets/23232232/21566848/e975f594-cee1-11e6-8908-47b41b23b42a.png)
所有后端user-config.json都按照如下填写
![image](https://cloud.githubusercontent.com/assets/23232232/21566854/f6d139a6-cee1-11e6-9316-056b14f3966e.png)

**Comment by glzjin** [comment]
@masonyeung 你的运行参数是？

**Comment by masonyeung** [comment]
赵老师，恕我不知道您指运行参数是指这个吗？
![image](https://cloud.githubusercontent.com/assets/23232232/21567256/dd849eee-cee5-11e6-951f-c35c7d4e8fa8.png)

**Comment by masonyeung** [comment]
我用supervisord运行后端的，与普通节点一样
![image](https://cloud.githubusercontent.com/assets/23232232/21567322/5a232826-cee6-11e6-8c79-31944c691acc.png)

**Comment by glzjin** [comment]
@masonyeung 你是怎么配置这个节点的 在管理面板里

**Comment by masonyeung** [comment]
![image](https://cloud.githubusercontent.com/assets/23232232/21567452/2d1e6510-cee7-11e6-9b4a-c01d94a1636b.png)

**Comment by glzjin** [comment]
@masonyeung 在 user-config.json 里添加一个配置项 verbose 值为 1 然后重启后端

**Comment by masonyeung** [comment]
按照一下配置，添加完后重启
![image](https://cloud.githubusercontent.com/assets/23232232/21567582/34f67ec0-cee8-11e6-9142-576a38f24091.png)

这边正常
![image](https://cloud.githubusercontent.com/assets/23232232/21567619/6f9b9470-cee8-11e6-9953-40240c074a82.png)

但是还是中转不了

**Comment by glzjin** [comment]
@masonyeung 看中转日志，反正这就不管我事了，自己检查节点之间连通性吧

**Comment by masonyeung** [comment]
好的，谢谢赵大！
