### ISSUE TITLE
赵大你好，问下添加新节点服务器的方法

### ISSUE THREAD

**Issue by hly9469** [kjukjuatnk/ss-panel-v3-mod#538]
我的方法是这样：
在面板主机数据库新建一个remote用户给予sspanel数据库访问权限，连接主机为“%”，然后在新节点服务器安装后端，配置文件数据库连接填写主机ip和remote相关信息，但是主面板新节点却始终是黄色的叹号无法使用，这是什么问题……

**Comment by glzjin** [comment]
@hly9469 发后端日志

**Comment by hly9469** [comment]
新节点后端我是用supervisord来运行的、、怎么找日志

**Comment by hly9469** [comment]
哦哦哦、找到了、在这里、我截取了部分、现在面板显示是正常的、之前主机也出现过这个问题、但不知怎么莫名其妙就好了
![mark](http://www.rufool.cn/blog/20170101/183714521.png)
![mark](http://www.rufool.cn/blog/20170101/183619768.png)
![mark](http://www.rufool.cn/blog/20170101/183627914.png)
![mark](http://www.rufool.cn/blog/20170101/183633864.png)

**Comment by hly9469** [comment]
显示正常、但连上还是上不了网、

**Comment by glzjin** [comment]
@hly9469 这叫显示正常？数据库都没连上

**Comment by hly9469** [comment]
呃、那我上面连接数据库的方法哪里有错吗……主句防火墙已经开启3306端口通过、下面是我主机新建的数据库账户和节点上的数据库配置信息
![mark](http://www.rufool.cn/blog/20170101/184402452.png)
![mark](http://www.rufool.cn/blog/20170101/184408613.png)
![mark](http://www.rufool.cn/blog/20170101/184414345.png)

**Comment by glzjin** [comment]
@hly9469 反正还是防火墙的问题吧 自己telnet一下3306

**Comment by hly9469** [comment]
嗯好、我试试

**Comment by hly9469** [comment]
经过我对防火墙的狂轰滥炸、现在数据库应该是连上了、但是……连上了ssr却还是不能联网、mu的日志是这样的：
![mark](http://www.rufool.cn/blog/20170101/193711520.png)

**Comment by glzjin** [comment]
@hly9469 自己检查节点防火墙端口开了没咯

**Comment by hly9469** [comment]
解决了、防火墙啥端口都开了、就是不好使、最后 chkconfig iptables off 。。谢谢赵大(* ￣3)(ε￣ *)

**Comment by CxiaoyuN** [comment]
你怎么搞好的？我也是一直黄色感叹号。是后端没连接好数据库，还是端口问题？

**Comment by hly9469** [comment]
防火墙的问题，没开放3306端口，以及用到的ssr连接端口，去iptables手动开下，或者干脆禁用iptables，命令为上面issue里的

**Comment by CxiaoyuN** [comment]
是前端还是后端的防火墙？能发一下你的命令代码吗？我试了几个没用。

**Comment by hly9469** [comment]
chkconfig iptables off 前后端都执行

**Comment by CxiaoyuN** [comment]
好的

**Comment by CxiaoyuN** [comment]
直接输入代码？我试了，没什么显示。在后台还是黄色感叹号

**Comment by CxiaoyuN** [comment]
@hly9469 你QQ多少，加，一下，我截图给你看看，我哪里错了

**Comment by hly9469** [comment]
弄了个群，167648229
